<?php
return [
    [
        "category" => "Chụp Ảnh Tết",
        "category_slug" => "chup-anh-tet",
        "description" => "Tôn vinh năm mới với phong cách truyền thống và hiện đại",
        "tiers" => [
            [
                "id" => "tet-co-ban",
                "name" => "Cơ Bản",
                "price_num" => 2500000,
                "price" => "2,500,000",
                "duration" => "2 giờ",
                "photos" => "100+ ảnh chỉnh sửa",
                "features" => ["Ảnh chân dung gia đình (studio hoặc ngoài trời)", "Chuẩn bị trang phục Áo Dài truyền thống", "Thư viện kỹ thuật số có tải xuống", "Giao hàng nhanh (5 ngày làm việc)"],
                "cta" => "Đặt Lịch",
                "featured" => false,
            ],
            [
                "id" => "tet-premium",
                "name" => "Premium",
                "price_num" => 4500000,
                "price" => "4,500,000",
                "duration" => "4 giờ",
                "photos" => "200+ ảnh chỉnh sửa",
                "features" => ["Phiên tháo dài với gia đình mở rộng", "Thay quần áo nhiều lần", "Chụp tại 2 địa điểm", "Album cao cấp (20 trang)", "Chỉnh sửa ưu tiên", "Ảnh in bao gồm"],
                "cta" => "Đặt Lịch",
                "featured" => true,
            ],
            [
                "id" => "tet-cao-cap",
                "name" => "Cao Cấp",
                "price_num" => 7000000,
                "price" => "7,000,000",
                "duration" => "Cả ngày",
                "photos" => "400+ ảnh chỉnh sửa",
                "features" => ["Chụp toàn bộ ngày", "Không giới hạn địa điểm", "Hỗ trợ trang phục chuyên nghiệp", "Album cao cấp + in trên canvas", "Video tóm tắt", "Thư viện riêng tư trực tuyến", "Hỗ trợ 6 tháng"],
                "cta" => "Đặt Lịch",
                "featured" => false,
            ],
        ],
    ],
    [
        "category" => "Chụp Ảnh Cưới",
        "category_slug" => "chup-anh-cuoi",
        "description" => "Ghi lại ngày đặc biệt với sự xuất sắc nghệ thuật",
        "tiers" => [
            [
                "id" => "cuoi-nua-ngay",
                "name" => "Nửa Ngày",
                "price_num" => 8000000,
                "price" => "8,000,000",
                "duration" => "6 giờ",
                "photos" => "300+ ảnh chỉnh sửa",
                "features" => ["Chụp lễ + tiệc", "2 nhiếp ảnh gia", "Thư viện kỹ thuật số", "Xem trước chỉnh sửa cùng ngày", "Giao hàng USB"],
                "cta" => "Đặt Lịch",
                "featured" => false,
            ],
            [
                "id" => "cuoi-toan-ngay",
                "name" => "Toàn Ngày",
                "price_num" => 14000000,
                "price" => "14,000,000",
                "duration" => "12 giờ",
                "photos" => "600+ ảnh chỉnh sửa",
                "features" => ["Chụp cả ngày (chuẩn bị đến tiễn)", "2 nhiếp ảnh gia + 1 quay video", "Album cao cấp (40 trang)", "Chụp kỷ niệm bao gồm", "Video tóm tắt", "Lựa chọn ảnh in", "Thư viện trực tuyến vĩnh viễn"],
                "cta" => "Đặt Lịch",
                "featured" => true,
            ],
            [
                "id" => "cuoi-premium",
                "name" => "Gói Premium",
                "price_num" => 20000000,
                "price" => "20,000,000",
                "duration" => "2 ngày",
                "photos" => "1000+ ảnh chỉnh sửa",
                "features" => ["Chụp 2 ngày (tập duyệt + cưới)", "3 nhiếp ảnh gia + 2 quay video", "Album bìa da cao cấp", "Chụp kỷ niệm + tiền hôn nhân", "Video 4K có chỉnh sửa chuyên nghiệp", "In sách bàn cà phê", "Giao hàng kéo dài (60 ngày)"],
                "cta" => "Đặt Lịch",
                "featured" => false,
            ],
        ],
    ],
    [
        "category" => "Ảnh Kỷ Niệm & Sự Kiện Đặc Biệt",
        "category_slug" => "anh-ky-niem",
        "description" => "Tôn vinh những cột mốc với những bức chân dung bất biến",
        "tiers" => [
            [
                "id" => "kyniem-co-dien",
                "name" => "Cổ Điển",
                "price_num" => 1800000,
                "price" => "1,800,000",
                "duration" => "1.5 giờ",
                "photos" => "75+ ảnh chỉnh sửa",
                "features" => ["Phiên chân dung cặp đôi", "Địa điểm tùy chọn", "Thay đổi trang phục 1 lần", "Thư viện kỹ thuật số", "Giao hàng nhanh"],
                "cta" => "Đặt Lịch",
                "featured" => false,
            ],
            [
                "id" => "kyniem-cao-cap",
                "name" => "Cao Cấp",
                "price_num" => 3200000,
                "price" => "3,200,000",
                "duration" => "3 giờ",
                "photos" => "150+ ảnh chỉnh sửa",
                "features" => ["Phiên cặp dài hạn", "Nhiều địa điểm", "Thay đổi trang phục 3 lần", "Ảnh nhóm gia đình bao gồm", "Album nhỏ (10 trang)", "Lựa chọn in"],
                "cta" => "Đặt Lịch",
                "featured" => true,
            ],
            [
                "id" => "kyniem-bach-kim",
                "name" => "Bạch Kim",
                "price_num" => 5500000,
                "price" => "5,500,000",
                "duration" => "5 giờ",
                "photos" => "250+ ảnh chỉnh sửa",
                "features" => ["Chụp lễ kỷ niệm đầy đủ", "Không giới hạn địa điểm", "Trang phục chuyên nghiệp", "Album cao cấp (20 trang)", "In trên canvas (2)", "Video cắt ghép", "Thư viện riêng tư"],
                "cta" => "Đặt Lịch",
                "featured" => false,
            ],
        ],
    ],
];
